# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0002_auto_20180329_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='password',
            field=models.CharField(default='', max_length=64),
        ),
    ]
