# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0004_auto_20180329_0237'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rc', models.IntegerField(default=-2)),
                ('rs', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
